<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 1" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="/Users/progh2/dgspythonstudy2017/0507_Class/Family.py" status="error" test="Family" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/Users/progh2/.p2/pool/plugins/org.python.pydev_5.7.0.201704111357/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/Users/progh2/dgspythonstudy2017/0507_class/Family.py", line 1, in <module>
    from __main__ import name
ImportError: cannot import name 'name'
ERROR: Module: Family could not be imported (file: /Users/progh2/dgspythonstudy2017/0507_Class/Family.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="0507_Class 0507_Class"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
